import { OBTests } from "../OBTests";
import Test from "./Test";

export default function Tests() {
	const tests = OBTests;
	let id = localStorage.getItem("generalTestID");
	const questions = tests.find((test) => test.id == id);
	return (
		<div dir="rtl" className="flex flex-col gap-6 p-5 lg:mx-2">
			<Test
				no={questions.no1}
				question={questions.questions1}
				picture={questions.picture1}
				g1={questions.g1_1}
				g2={questions.g1_2}
				g3={questions.g1_3}
				g4={questions.g1_4}
                answer={questions.answer1}
			/>
			<Test
				no={questions.no2}
				question={questions.questions2}
				picture={questions.picture2}
				g1={questions.g2_1}
				g2={questions.g2_2}
				g3={questions.g2_3}
				g4={questions.g2_4}
                answer={questions.answer2}
			/>
			<Test
				no={questions.no3}
				question={questions.questions3}
				picture={questions.picture3}
				g1={questions.g3_1}
				g2={questions.g3_2}
				g3={questions.g3_3}
				g4={questions.g3_4}
                answer={questions.answer3}
			/>
			<Test
				no={questions.no4}
				question={questions.questions4}
				picture={questions.picture4}
				g1={questions.g4_1}
				g2={questions.g4_2}
				g3={questions.g4_3}
				g4={questions.g4_4}
                answer={questions.answer4}
			/>
			<Test
				no={questions.no5}
				question={questions.questions5}
				picture={questions.picture5}
				g1={questions.g5_1}
				g2={questions.g5_2}
				g3={questions.g5_3}
				g4={questions.g5_4}
                answer={questions.answer5}
			/>
			<Test
				no={questions.no6}
				question={questions.questions6}
				picture={questions.picture6}
				g1={questions.g6_1}
				g2={questions.g6_2}
				g3={questions.g6_3}
				g4={questions.g6_4}
                answer={questions.answer6}
			/>
			<Test
				no={questions.no7}
				question={questions.questions7}
				picture={questions.picture7}
				g1={questions.g7_1}
				g2={questions.g7_2}
				g3={questions.g7_3}
				g4={questions.g7_4}
                answer={questions.answer7}
			/>
			<Test
				no={questions.no8}
				question={questions.questions8}
				picture={questions.picture8}
				g1={questions.g8_1}
				g2={questions.g8_2}
				g3={questions.g8_3}
				g4={questions.g8_4}
                answer={questions.answer8}
			/>
			<Test
				no={questions.no9}
				question={questions.questions9}
				picture={questions.picture9}
				g1={questions.g9_1}
				g2={questions.g9_2}
				g3={questions.g9_3}
				g4={questions.g9_4}
                answer={questions.answer9}
			/>
			<Test
				no={questions.no10}
				question={questions.questions10}
				picture={questions.picture10}
				g1={questions.g10_1}
				g2={questions.g10_2}
				g3={questions.g10_3}
				g4={questions.g10_4}
                answer={questions.answer10}
			/>
			<Test
				no={questions.no11}
				question={questions.questions11}
				picture={questions.picture11}
				g1={questions.g11_1}
				g2={questions.g11_2}
				g3={questions.g11_3}
				g4={questions.g11_4}
                answer={questions.answer11}
			/>
			<Test
				no={questions.no12}
				question={questions.questions12}
				picture={questions.picture12}
				g1={questions.g12_1}
				g2={questions.g12_2}
				g3={questions.g12_3}
				g4={questions.g12_4}
                answer={questions.answer12}
			/>
			<Test
				no={questions.no13}
				question={questions.questions13}
				picture={questions.picture13}
				g1={questions.g13_1}
				g2={questions.g13_2}
				g3={questions.g13_3}
				g4={questions.g13_4}
                answer={questions.answer13}
			/>
			<Test
				no={questions.no14}
				question={questions.questions14}
				picture={questions.picture14}
				g1={questions.g14_1}
				g2={questions.g14_2}
				g3={questions.g14_3}
				g4={questions.g14_4}
                answer={questions.answer14}
			/>
			<Test
				no={questions.no15}
				question={questions.questions15}
				picture={questions.picture15}
				g1={questions.g15_1}
				g2={questions.g15_2}
				g3={questions.g15_3}
				g4={questions.g15_4}
                answer={questions.answer15}
			/>
			<Test
				no={questions.no16}
				question={questions.questions16}
				picture={questions.picture16}
				g1={questions.g16_1}
				g2={questions.g16_2}
				g3={questions.g16_3}
				g4={questions.g16_4}
                answer={questions.answer16}
			/>
			<Test
				no={questions.no17}
				question={questions.questions17}
				picture={questions.picture17}
				g1={questions.g17_1}
				g2={questions.g17_2}
				g3={questions.g17_3}
				g4={questions.g17_4}
                answer={questions.answer17}
			/>
			<Test
				no={questions.no18}
				question={questions.questions18}
				picture={questions.picture18}
				g1={questions.g18_1}
				g2={questions.g18_2}
				g3={questions.g18_3}
				g4={questions.g18_4}
                answer={questions.answer18}
			/>
			<Test
				no={questions.no19}
				question={questions.questions19}
				picture={questions.picture19}
				g1={questions.g19_1}
				g2={questions.g19_2}
				g3={questions.g19_3}
				g4={questions.g19_4}
                answer={questions.answer19}
			/>
			<Test
				no={questions.no20}
				question={questions.questions20}
				picture={questions.picture20}
				g1={questions.g20_1}
				g2={questions.g20_2}
				g3={questions.g20_3}
				g4={questions.g20_4}
                answer={questions.answer20}
			/>
			<Test
				no={questions.no21}
				question={questions.questions21}
				picture={questions.picture21}
				g1={questions.g21_1}
				g2={questions.g21_2}
				g3={questions.g21_3}
				g4={questions.g21_4}
                answer={questions.answer21}
			/>
			<Test
				no={questions.no22}
				question={questions.questions22}
				picture={questions.picture22}
				g1={questions.g22_1}
				g2={questions.g22_2}
				g3={questions.g22_3}
				g4={questions.g22_4}
                answer={questions.answer22}
			/>
			<Test
				no={questions.no23}
				question={questions.questions23}
				picture={questions.picture23}
				g1={questions.g23_1}
				g2={questions.g23_2}
				g3={questions.g23_3}
				g4={questions.g23_4}
                answer={questions.answer23}
			/>
			<Test
				no={questions.no24}
				question={questions.questions24}
				picture={questions.picture24}
				g1={questions.g24_1}
				g2={questions.g24_2}
				g3={questions.g24_3}
				g4={questions.g24_4}
                answer={questions.answer24}
			/>
			<Test
				no={questions.no25}
				question={questions.questions25}
				picture={questions.picture25}
				g1={questions.g25_1}
				g2={questions.g25_2}
				g3={questions.g25_3}
				g4={questions.g25_4}
                answer={questions.answer25}
			/>
			<Test
				no={questions.no26}
				question={questions.questions26}
				picture={questions.picture26}
				g1={questions.g26_1}
				g2={questions.g26_2}
				g3={questions.g26_3}
				g4={questions.g26_4}
                answer={questions.answer26}
			/>
			<Test
				no={questions.no27}
				question={questions.questions27}
				picture={questions.picture27}
				g1={questions.g27_1}
				g2={questions.g27_2}
				g3={questions.g27_3}
				g4={questions.g27_4}
                answer={questions.answer27}
			/>
			<Test
				no={questions.no28}
				question={questions.questions28}
				picture={questions.picture28}
				g1={questions.g28_1}
				g2={questions.g28_2}
				g3={questions.g28_3}
				g4={questions.g28_4}
                answer={questions.answer28}
			/>
			<Test
				no={questions.no29}
				question={questions.questions29}
				picture={questions.picture29}
				g1={questions.g29_1}
				g2={questions.g29_2}
				g3={questions.g29_3}
				g4={questions.g29_4}
                answer={questions.answer29}
			/>
			<Test
				no={questions.no30}
				question={questions.questions30}
				picture={questions.picture30}
				g1={questions.g30_1}
				g2={questions.g30_2}
				g3={questions.g30_3}
				g4={questions.g30_4}
                answer={questions.answer30}
			/>
		</div>
	);
}
